name: exif
version: 1.0.3
author: Taesu Pyo <pyotaesu@gmail.com>
description: Decode Exif data from tiff and jpeg files.
homepage: https://www.github.com/bigflood/dartexif
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  args: ^2.0.0
  collection: '^1.0.0'
  convert: ^3.0.0
  sprintf: ^6.0.0
dev_dependencies:
  test:
  archive: ^3.1.2
  path:
  http:
  json_annotation: ^4.0.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
  stream_channel:
executables:
  print_exif:
  